window.LEVELY_SCENARIOS = {
  missions: [
    {id:'m01',cat:'social',text:'3分以内に誰かから「乾杯しよ」を自然に引き出してください。',keyword:'乾杯'},
    {id:'m02',cat:'social',text:'誰か1人に「それマジ？」と言わせてください。',keyword:'マジ'},
    {id:'m03',cat:'staff',text:'スタッフと一度だけ目を合わせてください。理由は言わないこと。'},
    {id:'m04',cat:'social',text:'誰かにメニューを手渡してもらってください。'},
    {id:'m05',cat:'social',text:'全員を一度だけ同じ方向へ向かせてください。'},
    {id:'m06',cat:'social',text:'誰かから「なんで？」を引き出してください。',keyword:'なんで'},
    {id:'m07',cat:'social',text:'誰か1人に自分からではなく名前を呼ばせてください。'},
    {id:'m08',cat:'social',text:'60秒以内に2人を同時に笑わせてください。'},
    {id:'m09',cat:'social',text:'誰かに「ほんまに？」と言わせてください。',keyword:'ほんまに'},
    {id:'m10',cat:'social',text:'誰かに今日の日付を口に出させてください。'},
    {id:'m11',cat:'staff',text:'スタッフが近くを通った瞬間だけ、会話を1秒止めてください。'},
    {id:'m12',cat:'social',text:'誰か1人に自分のスマホを確認させてください。'},
    {id:'m13',cat:'social',text:'「そういえば」で始まる話題を自然に作ってください。',keyword:'そういえば'},
    {id:'m14',cat:'social',text:'誰か1人に「知らんけど」と言わせてください。',keyword:'知らんけど'},
    {id:'m15',cat:'social',text:'全員が同じタイミングで笑う瞬間を作ってください。'},
    {id:'m16',cat:'social',text:'誰かに「もう一回」を言わせてください。',keyword:'もう一回'},
    {id:'m17',cat:'social',text:'テーブルの誰かに店内を一度見回させてください。'},
    {id:'m18',cat:'social',text:'誰かに「何時？」と聞かせてください。',keyword:'何時'},
    {id:'m19',cat:'social',text:'1分以内に誰かから質問を2つ連続で受けてください。'},
    {id:'m20',cat:'social',text:'誰かがグラスまたはノンアルドリンクを持ち上げるきっかけを作ってください。'},
    {id:'m21',cat:'social',text:'誰か1人に「確かに」と言わせてください。',keyword:'確かに'},
    {id:'m22',cat:'social',text:'隣の人に一度だけ席の向きを変えてもらってください。'},
    {id:'m23',cat:'social',text:'誰かに「誰？」と言わせてください。',keyword:'誰'},
    {id:'m24',cat:'social',text:'誰かに写真の話題を出させてください。'},
    {id:'m25',cat:'social',text:'自分以外の2人が同じ単語を言う瞬間を作ってください。'},
    {id:'m26',cat:'social',text:'誰かに「やばい」を言わせてください。',keyword:'やばい'},
    {id:'m27',cat:'staff',text:'スタッフに自然に「ありがとう」と伝えてください。他の人には理由を言わないこと。',keyword:'ありがとう'},
    {id:'m28',cat:'social',text:'誰かに次の店・次の予定の話をさせてください。'},
    {id:'m29',cat:'social',text:'誰かに「え、待って」と言わせてください。',keyword:'待って'},
    {id:'m30',cat:'social',text:'2分以内に誰かの口から店名「LEVELY」を引き出してください。',keyword:'LEVELY'}
  ],
  events: [
    {"id": "e01", "cat": "karaoke", "title": "KARAOKE VOTE", "message": "次に歌う人を全員で3・2・1で一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e02", "cat": "karaoke", "title": "MIC KING", "message": "この中で一番カラオケが上手そうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e03", "cat": "karaoke", "title": "SECRET SINGER", "message": "一番ラブソングが似合いそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e04", "cat": "karaoke", "title": "LAST NOTE", "message": "直前に流れた曲の歌手名を早押しで答えろ。最初に正解した人が1人指名し、指名された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e05", "cat": "karaoke", "title": "CHORUS BATTLE", "message": "全員で次の曲のサビを10秒だけ歌え。最初に歌詞が止まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e06", "cat": "karaoke", "title": "NO SING", "message": "次の30秒、流れている曲を口ずさむのは禁止。最初に歌った人がドリンクを一口（ノンアルOK）。"},
    {"id": "e07", "cat": "karaoke", "title": "SONG MEMORY", "message": "5秒以内に全員1曲ずつカラオケの十八番を言え。言えなかった人はドリンクを一口（ノンアルOK）。"},
    {"id": "e08", "cat": "social", "title": "HIGH TENSION", "message": "この中で一番テンションが高い人を3・2・1で一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e09", "cat": "social", "title": "MOST POPULAR", "message": "今日一番モテそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e10", "cat": "social", "title": "SECRET PERSON", "message": "一番秘密が多そうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e11", "cat": "social", "title": "NIGHT OWL", "message": "今日このあと一番遅くまで起きていそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e12", "cat": "social", "title": "FIRST IMPRESSION", "message": "初対面でも一番仲良くなりやすそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e13", "cat": "social", "title": "PHONE CHECK", "message": "今日一番スマホを見ていそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e14", "cat": "social", "title": "LEVELY ADDICT", "message": "この店に一番また来そうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e15", "cat": "chaos", "title": "NG WORD", "message": "60秒間「マジ」禁止。最初に言った人がドリンクを一口（ノンアルOK）。", "keyword": "マジ"},
    {"id": "e16", "cat": "chaos", "title": "NG WORD", "message": "60秒間「やばい」禁止。最初に言った人がドリンクを一口（ノンアルOK）。", "keyword": "やばい"},
    {"id": "e17", "cat": "chaos", "title": "YES NO BAN", "message": "60秒間「はい」「いいえ」禁止。最初に言った人がドリンクを一口（ノンアルOK）。"},
    {"id": "e18", "cat": "chaos", "title": "QUESTION TRAP", "message": "60秒間、質問されたら質問で返せ。普通に答えてしまった最初の人がドリンクを一口（ノンアルOK）。"},
    {"id": "e19", "cat": "chaos", "title": "SILENT 10", "message": "今から10秒全員無言。最初に声を出した人がドリンクを一口（ノンアルOK）。"},
    {"id": "e20", "cat": "chaos", "title": "NO NAME", "message": "60秒間、人の名前を呼ぶのは禁止。最初に呼んだ人がドリンクを一口（ノンアルOK）。"},
    {"id": "e21", "cat": "chaos", "title": "LAST REACTION", "message": "スタッフの合図で全員同時に両手を上げろ。一番遅かった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e22", "cat": "staff", "title": "STAFF ATTACK", "message": "スタッフが選ぶ「今一番楽しそうな人」がドリンクを一口（ノンアルOK）。スタッフは5秒以内に1人指名せよ。"},
    {"id": "e23", "cat": "staff", "title": "STAFF VOTE", "message": "全員で「スタッフに一番気に入られそうな人」を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e24", "cat": "staff", "title": "STAFF EYE", "message": "スタッフと最初に目が合った人がドリンクを一口（ノンアルOK）。今から30秒スタート。"},
    {"id": "e25", "cat": "staff", "title": "STAFF JUDGE", "message": "スタッフがこの卓で一番怪しい人を1人指名。指名された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e26", "cat": "staff", "title": "STAFF CHOICE", "message": "スタッフがAかBのどちらかを宣言。全員同時にA/Bを選び、スタッフと違う側の人がドリンクを一口（ノンアルOK）。"},
    {"id": "e27", "cat": "staff", "title": "STAFF COUNT", "message": "スタッフが3・2・1とカウント。0で全員ポーズ。一人だけ違うポーズだった人がいればその人がドリンクを一口（ノンアルOK）。全員バラバラならスタッフが1人指名。"},
    {"id": "e28", "cat": "staff", "title": "STAFF TARGET", "message": "全員目を閉じろ。スタッフが1人を指名してから目を開ける。指名された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e29", "cat": "order", "title": "BLACK ORDER", "message": "次に何か注文した人が1人指名。指名された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e30", "cat": "order", "title": "BLACK ORDER", "message": "次に何か注文した人は左右どちらかを宣言。その側に座っている人全員がドリンクを一口（ノンアルOK）。"},
    {"id": "e31", "cat": "order", "title": "BLACK ORDER", "message": "次に何か注文した人が「グー・チョキ・パー」を1つ宣言。全員じゃんけんし、宣言された手を出した人がドリンクを一口（ノンアルOK）。"},
    {"id": "e32", "cat": "order", "title": "BLACK ORDER", "message": "次に何か注文した人が1〜5の数字を宣言。全員同時に指で1〜5を出し、一致した人がドリンクを一口（ノンアルOK）。"},
    {"id": "e33", "cat": "order", "title": "BLACK ORDER", "message": "次に何か注文した人が質問を1つ出す。5秒以内に答えられなかった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e34", "cat": "order", "title": "BLACK ORDER", "message": "次に何か注文した人の両隣がじゃんけん。負けた人がドリンクを一口（ノンアルOK）。"},
    {"id": "e35", "cat": "order", "title": "BLACK ORDER", "message": "次に何か注文した人以外で「一番次に注文しそうな人」を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e36", "cat": "vote", "title": "WHO KNOWS?", "message": "一番酔っているように見える人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e37", "cat": "vote", "title": "WHO KNOWS?", "message": "今日一番お金を使いそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e38", "cat": "vote", "title": "WHO KNOWS?", "message": "一番恋愛相談を受けていそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e39", "cat": "vote", "title": "WHO KNOWS?", "message": "一番寝起きが悪そうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e40", "cat": "vote", "title": "WHO KNOWS?", "message": "一番SNSを見ていそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e41", "cat": "vote", "title": "WHO KNOWS?", "message": "一番ゲームの裏を読んでいそうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e42", "cat": "vote", "title": "WHO KNOWS?", "message": "今日一番LEVELYに操られている人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e43", "cat": "duo", "title": "PAIR LINK", "message": "隣同士で相談なしに1〜5の数字を同時に言え。数字が違ったペアは2人ともドリンクを一口（ノンアルOK）。"},
    {"id": "e44", "cat": "duo", "title": "PAIR LINK", "message": "隣同士で同時に「海／山」を言え。違ったペアは2人ともドリンクを一口（ノンアルOK）。"},
    {"id": "e45", "cat": "duo", "title": "PAIR LINK", "message": "隣同士でじゃんけん。負けた人がドリンクを一口（ノンアルOK）。あいこはセーフ。"},
    {"id": "e46", "cat": "duo", "title": "PAIR LINK", "message": "2人組で相談なしに同じポーズを取れ。揃わなかったペアは2人ともドリンクを一口（ノンアルOK）。"},
    {"id": "e47", "cat": "duo", "title": "PAIR LINK", "message": "隣同士で同時に「犬／猫」を言え。違ったペアは2人ともドリンクを一口（ノンアルOK）。"},
    {"id": "e48", "cat": "duo", "title": "PAIR LINK", "message": "隣同士で同時に指で1〜3を出せ。数字が違ったペアは大きい数字を出した人がドリンクを一口（ノンアルOK）。"},
    {"id": "e49", "cat": "duo", "title": "PAIR LINK", "message": "隣同士で5秒見つめ合え。先に笑った人がドリンクを一口（ノンアルOK）。"},
    {"id": "e50", "cat": "secret", "title": "SECRET SIGNAL", "message": "全員目を閉じ、1人だけこっそり手を挙げろ。目を開けて全員で誰だったか投票。最多票の人が外れていたら、投票した側がドリンクを一口（ノンアルOK）。"},
    {"id": "e51", "cat": "secret", "title": "DOUBLE AGENT", "message": "一番最近LEVELYに来た人が30秒以内に自然に話題を変えろ。誰かに見破られたら本人、見破られなければ本人が1人指名し、指名された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e52", "cat": "secret", "title": "TRUST TEST", "message": "1人が好きな食べ物を本当かウソで答える。全員同時に本当/ウソを予想し、外した人がドリンクを一口（ノンアルOK）。"},
    {"id": "e53", "cat": "secret", "title": "LIAR", "message": "1人が昨日したことを本当かウソで話す。全員同時に判定し、外した人がドリンクを一口（ノンアルOK）。"},
    {"id": "e54", "cat": "secret", "title": "HIDDEN NUMBER", "message": "1人が1〜5を心の中で決める。他の全員は同時に予想。一致した人がいなければ決めた本人、一致した人がいれば本人がドリンクを一口（ノンアルOK）。"},
    {"id": "e55", "cat": "secret", "title": "WHO DID IT", "message": "全員目を閉じ、スタッフが1人を選ぶ。目を開けて10秒以内に全員で犯人を予想。外した人がドリンクを一口（ノンアルOK）。"},
    {"id": "e56", "cat": "secret", "title": "SECRET TARGET", "message": "全員で心の中に1人選び、3・2・1で一斉に指差せ。誰からも指されなかった人がいればその人が1人指名し、指名された人がドリンクを一口（ノンアルOK）。全員指されたら最多票の人。"},
    {"id": "e57", "cat": "speed", "title": "3 SECOND", "message": "順番に3秒以内で「赤いもの」を1つ言え。詰まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e58", "cat": "speed", "title": "3 SECOND", "message": "順番に3秒以内で大阪の駅名を1つ言え。同じ駅名を言うか詰まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e59", "cat": "speed", "title": "3 SECOND", "message": "順番に3秒以内で居酒屋メニューを1つ言え。詰まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e60", "cat": "speed", "title": "3 SECOND", "message": "順番に3秒以内でコンビニの商品を1つ言え。詰まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e61", "cat": "speed", "title": "3 SECOND", "message": "順番に3秒以内で動物を1つ言え。同じ答えか詰まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e62", "cat": "speed", "title": "3 SECOND", "message": "順番に3秒以内で都道府県を1つ言え。詰まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e63", "cat": "speed", "title": "3 SECOND", "message": "順番に3秒以内でカラオケ歌手を1人言え。詰まった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e64", "cat": "voice", "title": "VOICE TRAP", "message": "60秒間「マジ」がNGワード。最初に言った人がドリンクを一口（ノンアルOK）。音声判定を使える人はマイクON。", "keyword": "マジ"},
    {"id": "e65", "cat": "voice", "title": "VOICE TRAP", "message": "60秒間「やばい」がNGワード。最初に言った人がドリンクを一口（ノンアルOK）。音声判定を使える人はマイクON。", "keyword": "やばい"},
    {"id": "e66", "cat": "voice", "title": "VOICE TRAP", "message": "60秒間「ほんま」がNGワード。最初に言った人がドリンクを一口（ノンアルOK）。音声判定を使える人はマイクON。", "keyword": "ほんま"},
    {"id": "e67", "cat": "voice", "title": "VOICE TRAP", "message": "60秒間「なんで」がNGワード。最初に言った人がドリンクを一口（ノンアルOK）。音声判定を使える人はマイクON。", "keyword": "なんで"},
    {"id": "e68", "cat": "voice", "title": "VOICE HUNT", "message": "最初に「乾杯」と言った人がドリンクを一口（ノンアルOK）。音声判定を使える人はマイクON。", "keyword": "乾杯"},
    {"id": "e69", "cat": "voice", "title": "VOICE HUNT", "message": "最初に「LEVELY」と言った人が、好きな1人を指名。指名された人がドリンクを一口（ノンアルOK）。", "keyword": "LEVELY"},
    {"id": "e70", "cat": "voice", "title": "VOICE HUNT", "message": "最初に「ありがとう」と言った人がセーフ。その人が1人指名し、指名された人がドリンクを一口（ノンアルOK）。", "keyword": "ありがとう"},
    {"id": "e71", "cat": "mind", "title": "MIND READ", "message": "全員1〜5を同時に指で出せ。一番少ない数字を出した人がドリンクを一口（ノンアルOK）。同数なら該当者全員。"},
    {"id": "e72", "cat": "mind", "title": "MIND READ", "message": "全員同時に「犬／猫」を選べ。少数派がドリンクを一口（ノンアルOK）。同数なら全員セーフ。"},
    {"id": "e73", "cat": "mind", "title": "MIND READ", "message": "全員同時に「朝／夜」を選べ。少数派がドリンクを一口（ノンアルOK）。同数なら全員セーフ。"},
    {"id": "e74", "cat": "mind", "title": "MIND READ", "message": "全員同時にグー・チョキ・パーを出せ。一人だけ違う手ならその人がドリンクを一口（ノンアルOK）。全員バラバラなら全員セーフ。"},
    {"id": "e75", "cat": "mind", "title": "MIND READ", "message": "全員で一番笑いのツボが浅そうな人を一斉に指差せ。一番多く指された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e76", "cat": "mind", "title": "MIND READ", "message": "全員同時に1〜3を指で出せ。一番多かった数字を出した人全員がドリンクを一口（ノンアルOK）。"},
    {"id": "e77", "cat": "mind", "title": "MIND READ", "message": "全員同時に「YES／NO」を選べ。少数派がドリンクを一口（ノンアルOK）。同数ならスタッフが1人指名。"},
    {"id": "e78", "cat": "bar", "title": "THE BAR MOVES", "message": "次にスタッフが近くを通った瞬間、最後に気づいた人がドリンクを一口（ノンアルOK）。"},
    {"id": "e79", "cat": "bar", "title": "THE BAR MOVES", "message": "次に誰かがメニューを開いたら、その人を最初に指差した人がセーフ。最後まで指差せなかった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e80", "cat": "bar", "title": "THE BAR MOVES", "message": "店内で次に大きな音がしたら全員テーブルを1回タップ。最後の人がドリンクを一口（ノンアルOK）。"},
    {"id": "e81", "cat": "bar", "title": "THE BAR MOVES", "message": "次に曲が変わった瞬間、最初に気づいた人が1人指名。指名された人がドリンクを一口（ノンアルOK）。"},
    {"id": "e82", "cat": "bar", "title": "THE BAR MOVES", "message": "30秒以内に全員で同じポーズを完成させろ。最後まで違うポーズだった人がドリンクを一口（ノンアルOK）。"},
    {"id": "e83", "cat": "bar", "title": "THE BAR MOVES", "message": "次に誰かがスマホを触った瞬間、その人が左右どちらかを選ぶ。選ばれた側の隣人がドリンクを一口（ノンアルOK）。"},
    {"id": "e84", "cat": "bar", "title": "THE BAR MOVES", "message": "今から60秒、最初に席を立った人が1人指名。指名された人がドリンクを一口（ノンアルOK）。"}
  ]
};
