window.LEVELY_SCENARIOS = {
  missions: [
    {id:'m01',cat:'social',text:'3分以内に誰かから「乾杯しよ」を自然に引き出してください。',keyword:'乾杯'},
    {id:'m02',cat:'social',text:'誰か1人に「それマジ？」と言わせてください。',keyword:'マジ'},
    {id:'m03',cat:'staff',text:'スタッフと一度だけ目を合わせてください。理由は言わないこと。'},
    {id:'m04',cat:'social',text:'誰かにメニューを手渡してもらってください。'},
    {id:'m05',cat:'social',text:'全員を一度だけ同じ方向へ向かせてください。'},
    {id:'m06',cat:'social',text:'誰かから「なんで？」を引き出してください。',keyword:'なんで'},
    {id:'m07',cat:'social',text:'誰か1人に自分からではなく名前を呼ばせてください。'},
    {id:'m08',cat:'social',text:'60秒以内に2人を同時に笑わせてください。'},
    {id:'m09',cat:'social',text:'誰かに「ほんまに？」と言わせてください。',keyword:'ほんまに'},
    {id:'m10',cat:'social',text:'誰かに今日の日付を口に出させてください。'},
    {id:'m11',cat:'staff',text:'スタッフが近くを通った瞬間だけ、会話を1秒止めてください。'},
    {id:'m12',cat:'social',text:'誰か1人に自分のスマホを確認させてください。'},
    {id:'m13',cat:'social',text:'「そういえば」で始まる話題を自然に作ってください。',keyword:'そういえば'},
    {id:'m14',cat:'social',text:'誰か1人に「知らんけど」と言わせてください。',keyword:'知らんけど'},
    {id:'m15',cat:'social',text:'全員が同じタイミングで笑う瞬間を作ってください。'},
    {id:'m16',cat:'social',text:'誰かに「もう一回」を言わせてください。',keyword:'もう一回'},
    {id:'m17',cat:'social',text:'テーブルの誰かに店内を一度見回させてください。'},
    {id:'m18',cat:'social',text:'誰かに「何時？」と聞かせてください。',keyword:'何時'},
    {id:'m19',cat:'social',text:'1分以内に誰かから質問を2つ連続で受けてください。'},
    {id:'m20',cat:'social',text:'誰かがグラスまたはノンアルドリンクを持ち上げるきっかけを作ってください。'},
    {id:'m21',cat:'social',text:'誰か1人に「確かに」と言わせてください。',keyword:'確かに'},
    {id:'m22',cat:'social',text:'隣の人に一度だけ席の向きを変えてもらってください。'},
    {id:'m23',cat:'social',text:'誰かに「誰？」と言わせてください。',keyword:'誰'},
    {id:'m24',cat:'social',text:'誰かに写真の話題を出させてください。'},
    {id:'m25',cat:'social',text:'自分以外の2人が同じ単語を言う瞬間を作ってください。'},
    {id:'m26',cat:'social',text:'誰かに「やばい」を言わせてください。',keyword:'やばい'},
    {id:'m27',cat:'staff',text:'スタッフに自然に「ありがとう」と伝えてください。他の人には理由を言わないこと。',keyword:'ありがとう'},
    {id:'m28',cat:'social',text:'誰かに次の店・次の予定の話をさせてください。'},
    {id:'m29',cat:'social',text:'誰かに「え、待って」と言わせてください。',keyword:'待って'},
    {id:'m30',cat:'social',text:'2分以内に誰かの口から店名「LEVELY」を引き出してください。',keyword:'LEVELY'}
  ],
  events: [
    {id:'e01',cat:'karaoke',title:'LEVELY JACK',message:'曲が終わった瞬間、歌っていない人は3秒だけ無言で拍手してください。'},
    {id:'e02',cat:'karaoke',title:'LAST NOTE',message:'次の曲が終わったら、最初に曲名を言えた人が1ポイント。'},
    {id:'e03',cat:'karaoke',title:'SECRET CHORUS',message:'サビだけ全員同時に1フレーズ口ずさんでください。無理なら手拍子でもOK。'},
    {id:'e04',cat:'karaoke',title:'SILENT FAN',message:'歌っている人に気づかれないよう、残りの人だけで同じポーズをしてください。'},
    {id:'e05',cat:'karaoke',title:'MIC SWITCH',message:'次の曲の予約者を、会話だけで30秒以内に決めてください。'},
    {id:'e06',cat:'social',title:'PREDICTION',message:'LEVELYは予測します。90秒以内に誰かが「なんで？」と言います。'},
    {id:'e07',cat:'social',title:'PREDICTION',message:'LEVELYは予測します。60秒以内に誰かが店内を見回します。'},
    {id:'e08',cat:'social',title:'PREDICTION',message:'LEVELYは予測します。90秒以内に誰かが時間を確認します。'},
    {id:'e09',cat:'social',title:'PREDICTION',message:'LEVELYは予測します。60秒以内に2人が同時に笑います。'},
    {id:'e10',cat:'social',title:'PREDICTION',message:'LEVELYは予測します。2分以内に誰かが次の予定について話します。'},
    {id:'e11',cat:'chaos',title:'CHAOS MODE',message:'60秒間「マジ」禁止。言った人を最初に指摘できた人が勝ち。',keyword:'マジ'},
    {id:'e12',cat:'chaos',title:'CHAOS MODE',message:'60秒間カタカナ禁止。気づいた人はテーブルを1回タップ。'},
    {id:'e13',cat:'chaos',title:'CHAOS MODE',message:'次の60秒、質問に「はい／いいえ」で答えるのは禁止。'},
    {id:'e14',cat:'chaos',title:'REVERSE',message:'30秒間、質問されたら質問で返してください。'},
    {id:'e15',cat:'chaos',title:'ECHO',message:'次に誰かが笑ったら、全員1秒遅れて同じタイミングで笑ってください。'},
    {id:'e16',cat:'staff',title:'STAFF ATTACK',message:'スタッフがこの卓へ介入しました。30秒以内に誰か1人を笑わせてください。'},
    {id:'e17',cat:'staff',title:'STAFF SIGNAL',message:'スタッフが近くを通ったら、誰か1人だけ軽くうなずいてください。'},
    {id:'e18',cat:'staff',title:'STAFF VOTE',message:'スタッフが選んだ…という設定です。この中で一番今日のテンションが高い人を全員同時に指差してください。'},
    {id:'e19',cat:'staff',title:'STAFF INTERVENTION',message:'この卓には1人、LEVELYから秘密の役割を受け取っている人物がいます。'},
    {id:'e20',cat:'staff',title:'STAFF CHECK',message:'今から30秒、スタッフを見ないでください。最初に見た人が負け。'},
    {id:'e21',cat:'order',title:'BLACK ORDER',message:'次にドリンクまたはノンアルを注文した人は、秘密ミッションを1回交換できます。'},
    {id:'e22',cat:'order',title:'BLACK ORDER',message:'次に何か注文した人は、1人を選んでその人のミッション難易度を下げられます。'},
    {id:'e23',cat:'order',title:'BLACK ORDER',message:'次の注文者は「FAKE」を獲得。他の1人に偽ミッションを送ったことにできます。'},
    {id:'e24',cat:'order',title:'BLACK ORDER',message:'次に注文した人は、このラウンドのNGワードを1つ決められます。'},
    {id:'e25',cat:'order',title:'BLACK ORDER',message:'次に注文した人は「SHIELD」を獲得。次の罰ゲームを1回だけ無効化できます。'},
    {id:'e26',cat:'vote',title:'WHO KNOWS?',message:'全員同時に「今日一番秘密が多そうな人」を指差してください。'},
    {id:'e27',cat:'vote',title:'WHO KNOWS?',message:'全員同時に「この店に一番また来そうな人」を指差してください。'},
    {id:'e28',cat:'vote',title:'WHO KNOWS?',message:'全員同時に「今日一番LEVELYに操られている人」を指差してください。'},
    {id:'e29',cat:'vote',title:'WHO KNOWS?',message:'全員同時に「初対面でも仲良くなりやすそうな人」を指差してください。'},
    {id:'e30',cat:'vote',title:'WHO KNOWS?',message:'全員同時に「一番ゲームの裏を読んでいそうな人」を指差してください。'},
    {id:'e31',cat:'duo',title:'PAIR LINK',message:'隣同士で5秒以内に同じ数字（1〜5）を言ってください。揃えば成功。'},
    {id:'e32',cat:'duo',title:'PAIR LINK',message:'2人組を作り、相談なしで同時に「海／山」のどちらかを言ってください。'},
    {id:'e33',cat:'duo',title:'PAIR LINK',message:'隣の人と同時にグー・チョキ・パー。あいこならLEVELYに勝利。'},
    {id:'e34',cat:'duo',title:'PAIR LINK',message:'2人だけで10秒間、言葉を使わずに同じポーズを完成させてください。'},
    {id:'e35',cat:'duo',title:'PAIR LINK',message:'2人組で同時に好きなコンビニを言ってください。一致で成功。'},
    {id:'e36',cat:'secret',title:'SECRET SIGNAL',message:'1人だけが合図役です。誰が合図役か、残りの人は60秒以内に当ててください。'},
    {id:'e37',cat:'secret',title:'DOUBLE AGENT',message:'この中に「ゲームを邪魔する役」がいる…という設定で30秒だけ会話してください。'},
    {id:'e38',cat:'secret',title:'FALSE MEMORY',message:'LEVELYは「さっき誰かが店名を口にした」と主張しています。本当か全員で判定してください。'},
    {id:'e39',cat:'secret',title:'UNKNOWN RULE',message:'今から1分、LEVELYは秘密の禁止行動を1つ監視している…という設定です。全員で推理してください。'},
    {id:'e40',cat:'secret',title:'TRUST TEST',message:'1人を選び、その人の「今から言う一言」が本音か演技か全員で投票してください。'},
    {id:'e41',cat:'speed',title:'3 SECOND',message:'3秒以内に「赤いもの」を3つ答えてください。順番に1人ずつ。'},
    {id:'e42',cat:'speed',title:'3 SECOND',message:'3秒以内に大阪の駅名を2つ。詰まったら次の人へ。'},
    {id:'e43',cat:'speed',title:'3 SECOND',message:'3秒以内にカラオケでよく聞く言葉を2つ。'},
    {id:'e44',cat:'speed',title:'3 SECOND',message:'3秒以内に居酒屋メニューを3つ。'},
    {id:'e45',cat:'speed',title:'3 SECOND',message:'3秒以内に今日ここへ来るまでに見たものを2つ。'},
    {id:'e46',cat:'voice',title:'VOICE TRAP',message:'60秒間「マジ」がNGワード。音声判定を使える人はマイクをONにしてください。',keyword:'マジ'},
    {id:'e47',cat:'voice',title:'VOICE TRAP',message:'60秒間「やばい」がNGワード。音声判定を使える人はマイクをONにしてください。',keyword:'やばい'},
    {id:'e48',cat:'voice',title:'VOICE TRAP',message:'60秒間「ほんま」がNGワード。音声判定を使える人はマイクをONにしてください。',keyword:'ほんま'},
    {id:'e49',cat:'voice',title:'VOICE HUNT',message:'誰かが「乾杯」と言ったらLEVELYに捕捉されます。',keyword:'乾杯'},
    {id:'e50',cat:'voice',title:'VOICE HUNT',message:'誰かが「なんで」と言ったらLEVELYに捕捉されます。',keyword:'なんで'},
    {id:'e51',cat:'mind',title:'MIND READ',message:'全員1〜10の数字を1つ決め、同時に言ってください。同じ数字が出たら成功。'},
    {id:'e52',cat:'mind',title:'MIND READ',message:'全員「犬／猫」のどちらかを同時に言ってください。全員一致ならLEVELYに勝利。'},
    {id:'e53',cat:'mind',title:'MIND READ',message:'全員同時に「朝／夜」を選択。一番少数派だった人が次の仕掛け人。'},
    {id:'e54',cat:'mind',title:'MIND READ',message:'全員同時に指で1〜5を出してください。合計が偶数なら全員成功。'},
    {id:'e55',cat:'mind',title:'MIND READ',message:'全員、テーブル内で一番笑いのツボが浅そうな人を頭に浮かべてから同時に指差してください。'},
    {id:'e56',cat:'bar',title:'THE BAR MOVES',message:'店内で何か音が鳴った次の瞬間、最初に気づいた人が「LEVELY」と言ってください。'},
    {id:'e57',cat:'bar',title:'THE BAR MOVES',message:'次にスタッフが近くを通るまで、全員いつも通り会話してください。通った瞬間だけ無言。'},
    {id:'e58',cat:'bar',title:'THE BAR MOVES',message:'次に誰かが注文を考え始めたら、別の1人がそれを先に当ててください。'},
    {id:'e59',cat:'bar',title:'THE BAR MOVES',message:'今から2分間、店内で一番最初に聞こえた曲・音の話題を出した人が勝ち。'},
    {id:'e60',cat:'bar',title:'THE BAR MOVES',message:'LEVELYは今、この卓の空気を変えようとしています。30秒以内に全員の姿勢を一度変えてください。'}
  ]
};
